### ISSUE TITLE
inferring log syntax

### ISSUE THREAD

**Issue by ghosttie** [jtorjo/logwizard#41]
Instead of making the user copy some lines out of the log and paste them into the "Test Log Syntax" window it would be nicer to automatically read some lines from the file and try to guess the syntax without user intervention.

**Comment by jtorjo** [comment]
Long story short, this is what happens (or at least what should happen :) )

By default, I try to infer the syntax. Just in case I compute it wrong, I allow you to manually edit it. And since the syntax is usually not the easy to edit right from the beginning, I allow you to in-place find out if it's correct.

Let me know if this makes sense.
