### ISSUE TITLE
[Question] NLog Support

### ISSUE THREAD

**Issue by shaggygi** [jtorjo/logwizard#44]
Can you connect and view data that NLog stores in a specific database?

**Comment by jtorjo** [comment]
Hi,

Not yet, but I for sure plan to add this How urgent is this for you?
Also, if you could attach a small db that I could use for testing, that would help a lot.

Thanks!

Best,
John

**Comment by shaggygi** [comment]
Sounds great.  Thanks for the reply @jtorjo.  I don't need the feature until a few more months, so no rush.  Here is a link how to create a database.  NLog's wiki is pretty detailed.  https://github.com/nlog/NLog/wiki/Database-target

Hope this helps.

**Comment by jtorjo** [comment]
Coolio! Will look into it!

**Comment by shaggygi** [comment]
In addition to NLog database support, it would be nice to have NLog file target support, as well.  For example, be able to point to the target log file (or group of log files in a directory) and load within LogWizard.

**Comment by jtorjo** [comment]
@shaggygi NLog file target support is available. In case LW doesn't automatically find it correctly, you just need to set the right [syntax](https://github.com/jtorjo/logwizard/wiki/Syntax)

About a group of log files - are you talking about viewing each log separately?

**Comment by shaggygi** [comment]
It would be nice to select a directory with a bunch of logs or drag/drop all the logs you want to view.  It doesn't matter if you have to tab to each log.  However, in most cases the logs would be in same format just on different dates.  this would be helpful to see all in once view.  Just a thought.

I didn't realize LW already support NLog files.  I'll give it a try sometime soon then.  Thx

**Comment by jtorjo** [comment]
About dropping several files or a directory - I have to think about it. Should not be that difficult.
About NLog files - let me know how it goes!

**Comment by 304NotModified** [comment]
I think it would be nice if logwizard could read the NLog configuration, so it can easily find file logs or access db logs.

**Comment by jtorjo** [comment]
@304NotModified I would like to do this if there's enough interest in it. But my take is that it could get rather complicated - so I'd like to do it. If more people ask, I'll definitely look into it.

About log files - you can specify the syntax in LogWizard talk [here](https://github.com/jtorjo/logwizard/wiki/Syntax).

About databases - this is on my short-term todo list, so it will be here very soon (within 2 weeks - I believe). If you could send me a short log database you could spare (put it on dropbox or so; make sure it doesn't contain any confidential data :D)

I'd also like to add support for json files - but currently lack any examples - so that goes same for any json logs you might have.

I will delve more into NLog logs early next week.

**Comment by 304NotModified** [comment]
> @304NotModified I would like to do this if there's enough interest in it. But my take is that it could get rather complicated - so I'd like to do it. If more people ask, I'll definitely look into it.

Well reading the config is pretty because you can re-use C# from NLog for that. I can easily make a PR with a method:

```c#

List<String> GetNLogFilePaths(string configFile);

```

Which return the possible (regex) paths. E.g.

- input: "c:\build\nlog.config" (or "c:\build", nlog.config is the default)
- output:  "c:\log\*.log", "c:\internallog.log" 



input:

**Comment by jtorjo** [comment]
@304NotModified Getting the log files should be easy for LogWizard. 

How would I go about getting the log [syntax](https://github.com/jtorjo/logwizard/wiki/Syntax) of each?

**Comment by 304NotModified** [comment]
Good question. Well I have to check how the syntax works.

**Comment by jtorjo** [comment]
Sounds good. Let me know if anything is unclear or you run into any issues. You can also email me - here's [my email](http://torjo.com/contact.html)

**Comment by jtorjo** [comment]
@304NotModified @shaggygi 
Guys, note that I've added database support - it's in the latest code here. I will issue a release soon - hopefully by the end of the week.

I'm also working on automatically recognizing nlog and log4net pattern syntax - should be pretty awesome :P 

I will explain everything in a document

**Comment by jtorjo** [comment]
So guys, database support is here.
Huge nlog support is here - I will create a new release - probably tomorrow, with my latest changes.

Here's more info on support for [nlog/log4net](https://github.com/jtorjo/logwizard/wiki/loglibraries)

**Comment by shaggygi** [comment]
Thanks so much! I'll try to review with my team in the near future.

**Comment by jtorjo** [comment]
@shaggygi You're most welcome! As said, I will have a new release in a bit. Long story short, if you'll drop your nlog config file onto logwizard, it should automatically recognize all the database connection data. Let me know how it goes.
